services:
  - type: web
    name: checkmate3
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python preprocess_pipeline.py
    startCommand: gunicorn app:app --log-level debug --capture-output
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: FLASK_ENV
        value: development
    plan: free
